@extends('layouts.admin')

@section('page-title', 'Activity Report')

@section('content')
<div class="container-fluid py-4">
    <h3>Activity Report</h3>
    <p>Generated by: {{ auth()->user()->name }}</p>

    <div class="table-responsive mt-3">
        <table class="table table-hover">
            <thead class="table-light">
                <tr>
                    <th>Event Name</th>
                    <th>Organization</th>
                    <th>Status</th>
                    <th>Date</th>
                    <th>Participants</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['activities'] as $event)
                <tr>
                    <td>{{ $event->name }}</td>
                    <td>{{ $event->organization->name ?? '-' }}</td>
                    <td>{{ ucfirst($event->status) }}</td>
                    <td>{{ $event->date->format('M d, Y') }}</td>
                    <td>{{ $event->participants_count ?? 0 }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection
