@extends('layouts.admin')

@section('page-title', ucfirst($reportData['report_type']) . ' Report')

@section('content')
<div class="container-fluid py-4">
    <h3>{{ ucfirst($reportData['report_type']) }} Report</h3>
    <p>Generated by: {{ $reportData['generated_by'] }} on {{ $reportData['generated_at']->format('M d, Y H:i') }}</p>

    @if($reportData['report_type'] === 'users')
        <div class="table-responsive mt-3">
            <table class="table table-hover">
                <thead class="table-light">
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Status</th>
                        <th>Date Joined</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($reportData['data'] as $user)
                    <tr>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ ucfirst($user->role) }}</td>
                        <td>{{ $user->email_verified_at ? 'Verified' : 'Pending' }}</td>
                        <td>{{ $user->created_at->format('M d, Y') }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

    @elseif($reportData['report_type'] === 'organizations')
        <div class="table-responsive mt-3">
            <table class="table table-hover">
                <thead class="table-light">
                    <tr>
                        <th>Name</th>
                        <th>Category</th>
                        <th>Status</th>
                        <th>Officer</th>
                        <th>Members Count</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($reportData['data'] as $org)
                    <tr>
                        <td>{{ $org->name }}</td>
                        <td>{{ $org->category }}</td>
                        <td>{{ ucfirst($org->approval_status) }}</td>
                        <td>{{ $org->officer->name ?? '-' }}</td>
                        <td>{{ $org->memberships->count() }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

    @elseif($reportData['report_type'] === 'activities')
        <div class="table-responsive mt-3">
            <table class="table table-hover">
                <thead class="table-light">
                    <tr>
                        <th>Event Name</th>
                        <th>Organization</th>
                        <th>Status</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($reportData['data']['events'] as $event)
                    <tr>
                        <td>{{ $event->name }}</td>
                        <td>{{ $event->organization->name ?? '-' }}</td>
                        <td>{{ ucfirst($event->status) }}</td>
                        <td>{{ $event->date->format('M d, Y') }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

    @else
        <p>No data available for this report type.</p>
    @endif
</div>
@endsection
