<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ ucfirst($reportData['report_type']) }} Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        h2 { color: #222; margin-bottom: 5px; }
        p { margin: 0 0 10px 0; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        table, th, td { border: 1px solid #aaa; }
        th, td { padding: 6px 8px; text-align: left; }
        th { background-color: #f2f2f2; }
    </style>
</head>
<body>

<h2>{{ ucfirst($reportData['report_type']) }} Report</h2>
<p>Generated at: {{ $reportData['generated_at']->format('M d, Y H:i') }}</p>
<p>Generated by: {{ $reportData['generated_by'] }}</p>

@if($reportData['report_type'] === 'users')
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Status</th>
                <th>Date Joined</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData['data'] as $user)
            <tr>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ ucfirst($user->role) }}</td>
                <td>{{ ucfirst($user->status ?? 'Pending') }}</td>
                <td>{{ $user->created_at->format('M d, Y') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
@endif

@if($reportData['report_type'] === 'organizations')
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Category</th>
                <th>Officer</th>
                <th>Status</th>
                <th>Members Count</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData['data'] as $org)
            <tr>
                <td>{{ $org->name }}</td>
                <td>{{ $org->category }}</td>
                <td>{{ $org->officer->name ?? 'N/A' }}</td>
                <td>{{ ucfirst($org->approval_status ?? 'Pending') }}</td>
                <td>{{ $org->memberships->count() }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
@endif

@if($reportData['report_type'] === 'activities')
    <table>
        <thead>
            <tr>
                <th>Event Name</th>
                <th>Organization</th>
                <th>Status</th>
                <th>Date</th>
                <th>Participants</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData['data']['events'] as $event)
            <tr>
                <td>{{ $event->name }}</td>
                <td>{{ $event->organization->name ?? 'N/A' }}</td>
                <td>{{ ucfirst($event->status) }}</td>
                <td>{{ $event->date->format('M d, Y') }}</td>
                <td>{{ $event->memberships->count() }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
@endif

@if($reportData['report_type'] === 'overview')
    <table>
        <thead>
            <tr>
                <th>Metric</th>
                <th>Count</th>
            </tr>
        </thead>
        <tbody>
            <tr><td>Total Users</td><td>{{ $reportData['data']['users_count'] }}</td></tr>
            <tr><td>Total Organizations</td><td>{{ $reportData['data']['organizations_count'] }}</td></tr>
            <tr><td>Total Events</td><td>{{ $reportData['data']['events_count'] }}</td></tr>
            <tr><td>Total Memberships</td><td>{{ $reportData['data']['memberships_count'] }}</td></tr>
        </tbody>
    </table>
@endif

</body>
</html>
